/* Static application markup; no model or MCP data is inserted as HTML. */
const backendSection = document.getElementById('backendSettings');
backendSection.innerHTML = `
<h3>Ollama</h3><p class="settings-note">Ollama inference, streamed through June's backend. No Python service or browser CORS configuration is required.</p>
<form id="ollamaSettingsForm" class="backend-form">
<label class="stacked-setting">Ollama base URL<input id="settingBackendUrl" type="url" value="http://127.0.0.1:11434" required></label>
<label class="setting-row"><span>Allow a remote Ollama server<small>Remote servers receive messages and retrieved source code. HTTPS is required. A local Ollama endpoint can also use cloud models; choose local model weights for offline use.</small></span><input id="allowRemoteOllama" type="checkbox"></label>
<label class="stacked-setting">Bearer-token environment variable (optional)<input id="ollamaTokenEnv" placeholder="OLLAMA_API_KEY" autocomplete="off"><small>Enter the variable name, never the secret. Set it before starting June.</small></label>
<label class="setting-row"><span>Maximum agent rounds<small>Stops a run before an unbounded tool loop.</small></span><input id="agentStepLimit" type="number" min="1" max="20" required></label>
<details class="advanced-settings"><summary>Agent permissions</summary><p class="settings-note">Chat and Plan can inspect an open project's files. Agent edits, terminal commands, and every MCP tool call always require approval.</p>
<label class="setting-row"><span>Offer file-edit tools<small>Disabled by default. Each proposed edit is shown before it is applied.</small></span><input id="agentWrites" type="checkbox"></label>
<label class="setting-row"><span>Offer terminal tools<small>Not an OS sandbox. Approved commands run with your permissions, including access outside the project and network access.</small></span><input id="agentTerminal" type="checkbox"></label></details>
<div class="backend-actions"><button id="testBackendBtn" class="secondary-button" type="submit">Save &amp; connect</button><button id="refreshModelsBtn" class="quiet-button" type="button" data-backend-action="models">Refresh models</button></div><p id="backendTestResult" class="settings-note" role="status">Not connected.</p><div id="installedModelList" class="installed-models"></div>
</form>`;
const backendTab = document.getElementById('backendTab');
backendTab.innerHTML = '<span data-icon="plug"></span>Ollama';
const nav = document.querySelector('.settings-nav');
nav.insertAdjacentHTML('beforeend', `<button role="tab" id="performanceSettingsTab" data-settings="performance" aria-selected="false" aria-controls="performanceSettings" tabindex="-1"><span data-icon="sliders"></span>Performance</button><button role="tab" id="ragSettingsTab" data-settings="rag" aria-selected="false" aria-controls="ragSettings" tabindex="-1"><span data-icon="search"></span>Project RAG</button><button role="tab" id="mcpSettingsTab" data-settings="mcp" aria-selected="false" aria-controls="mcpSettings" tabindex="-1"><span data-icon="sliders"></span>MCP servers</button>`);
document.querySelector('.settings-content').insertAdjacentHTML('beforeend', `
<section id="performanceSettings" role="tabpanel" aria-labelledby="performanceSettingsTab" hidden><h3>Performance profiles</h3><p class="settings-note">Choose a profile for Ollama requests. Device and token settings apply to chat, summaries, and embeddings. June can restart only an Ollama server it started itself.</p>
<form id="performanceSettingsForm" class="backend-form">
<label class="stacked-setting">Profile<select id="performanceProfileSelect"></select></label><div class="backend-actions"><button id="performanceAdd" type="button" class="quiet-button">Duplicate profile</button><button id="performanceDelete" type="button" class="danger-button">Delete profile</button></div>
<label class="stacked-setting">Profile name<input id="performanceName" maxlength="80" required></label>
<label class="stacked-setting">Processing device<select id="performanceDevice"><option value="auto">GPU + CPU (Ollama automatic)</option><option value="cpu">CPU only</option><option value="gpu">GPU only (require full offload)</option></select><small>GPU only checks the loaded model before a reply and stops if Ollama reports CPU residency.</small></label>
<div class="backend-grid"><label>Context window<input id="ollamaContext" type="number" min="2048" max="262144" required></label><label>Max output tokens<input id="ollamaOutput" type="number" min="128" max="32768" required></label><label>Temperature<input id="ollamaTemperature" type="number" min="0" max="2" step="0.05" required></label><label>Keep model loaded<select id="ollamaKeepAlive"><option value="0">Unload after use</option><option value="1m">1 minute</option><option value="5m">5 minutes</option><option value="10m">10 minutes</option><option value="30m">30 minutes</option></select></label></div>
<details class="advanced-settings"><summary>Advanced Ollama options</summary><div class="backend-grid"><label>CPU threads<input id="performanceThreads" type="number" min="1" max="256" placeholder="Ollama default"></label><label>Batch size<input id="performanceBatch" type="number" min="1" max="4096" placeholder="Ollama default"></label><label>Main GPU index<input id="performanceMainGpu" type="number" min="0" max="31" placeholder="Ollama default"><small>Leave blank unless selecting a GPU explicitly. Indices start at 0 within Ollama's selected GPU backend; index 1 needs at least two GPUs in that backend.</small></label><label>Memory mapping<select id="performanceMmap"><option value="auto">Ollama default</option><option value="on">On</option><option value="off">Off</option></select></label></div>
<label class="setting-row"><span>Let June start Ollama<small>Only local HTTP servers are supported. June starts ollama serve and stops only its own process when settings change or June quits.</small></span><input id="performanceManaged" type="checkbox"></label>
<label class="stacked-setting">Vulkan backend<select id="performanceVulkan"><option value="auto">Ollama default</option><option value="on">On</option><option value="off">Off</option></select><small>Vulkan is a server startup option. It applies only when June starts Ollama.</small></label><label class="stacked-setting">Flash Attention<select id="performanceFlashAttention"><option value="auto">Ollama default</option><option value="on">On</option><option value="off">Off</option></select><small>Applies when June starts Ollama and the selected backend supports it.</small></label></details>
<button class="secondary-button" type="submit">Save and apply profile</button></form><p id="performanceStatus" class="settings-note" role="status"></p><details id="performanceDiagnosticsDetails" class="advanced-settings"><summary>Ollama diagnostics and logs</summary><button id="performanceRefreshDiagnostics" class="quiet-button" type="button">Refresh diagnostics</button><pre id="performanceDiagnostics" class="settings-note" style="white-space:pre-wrap;overflow-wrap:anywhere;max-height:18rem;overflow:auto"></pre></details></section>
<section id="ragSettings" role="tabpanel" aria-labelledby="ragSettingsTab" hidden><h3>Project retrieval</h3><p class="settings-note">Index source files, then retrieve relevant chunks for each request. Citations point to real file and line ranges. Chats and memory-library records are not indexed.</p>
<form id="ragSettingsForm" class="backend-form"><label class="setting-row"><span>Use RAG in chats<small>Off for temporary sessions. You can also switch it off in the composer.</small></span><input id="ragEnabled" type="checkbox"></label>
<label class="setting-row"><span>Retrieval mode</span><select id="ragMode"><option value="lexical">Keyword retrieval</option><option value="hybrid">Hybrid: embeddings + keywords</option></select></label>
<label class="stacked-setting">Ollama embedding model<select id="ragEmbeddingModel"><option value="">Choose an installed model</option></select><small>Hybrid mode calls /api/embed. Pull an embedding model separately before indexing.</small></label>
<div class="backend-grid"><label>Chunks per request<input id="ragTopK" type="number" min="1" max="12" required></label><label>Maximum source files<input id="ragMaxFiles" type="number" min="1" max="10000" required></label><label>Maximum chunks<input id="ragMaxChunks" type="number" min="1" max="10000" required></label></div>
<button class="secondary-button" type="submit">Save retrieval settings</button></form>
<div class="backend-card"><strong id="ragProjectLabel">Select a project</strong><p id="ragIndexStatus" class="settings-note" role="status">No project selected.</p><div class="backend-actions"><button id="indexProjectBtn" class="secondary-button" data-backend-action="index">Index / update project</button><button id="cancelIndexBtn" class="quiet-button" data-backend-action="cancel-index" hidden>Cancel indexing</button><button id="clearIndexBtn" class="danger-button" data-backend-action="clear-index">Clear index</button></div></div>
<p class="settings-note">Indexes are stored locally in June's user-data directory as unencrypted SQLite. Generated folders, credential filenames, binaries, symbolic links, hard links, and oversized files are excluded. In Git projects, ignore rules are respected. Inspect your repository for secrets embedded in ordinary source files before indexing. Reindex after edits; stale chunks are excluded at retrieval time.</p></section>
<section id="mcpSettings" role="tabpanel" aria-labelledby="mcpSettingsTab" hidden><h3>MCP tool servers</h3><p class="settings-note">Connect a trusted local process or Streamable HTTP endpoint. Connections are manual, tool access is opt-in, and each agent tool call requires approval. Temporary sessions do not use MCP.</p><div id="mcpServerList"></div>
<details id="mcpEditor" class="advanced-settings"><summary>Add / edit a server</summary><form id="mcpServerForm" class="backend-form"><input id="mcpServerId" type="hidden"><label class="stacked-setting">Name<input id="mcpServerName" maxlength="80" required></label><label class="setting-row"><span>Transport</span><select id="mcpTransport"><option value="stdio">Local process (stdio)</option><option value="http">Streamable HTTP</option></select></label>
<div id="mcpStdioFields"><label class="stacked-setting">Executable<input id="mcpCommand" placeholder="C:\\Program Files\\nodejs\\node.exe"></label><label class="stacked-setting">Arguments as a JSON array<textarea id="mcpArgs" rows="3" placeholder='["C:\\\\Tools\\\\my-server.mjs"]'>[]</textarea><small>No shell is used. Use an actual executable, not an npx.cmd / .bat wrapper.</small></label><label class="stacked-setting">Environment variables to forward (names only)<input id="mcpEnvNames" placeholder="MY_SERVICE_TOKEN"></label></div>
<div id="mcpHttpFields" hidden><label class="stacked-setting">MCP endpoint<input id="mcpUrl" type="url" placeholder="http://127.0.0.1:3000/mcp"></label><label class="setting-row"><span>Allow a remote HTTPS server</span><input id="mcpAllowRemote" type="checkbox"></label><label class="stacked-setting">Bearer-token environment variable (optional)<input id="mcpTokenEnv" autocomplete="off" placeholder="MCP_SERVICE_TOKEN"></label></div>
<p class="settings-note">This client supports MCP tools, stdio, and Streamable HTTP. OAuth sign-in, resources, prompts, and server-initiated sampling are not enabled.</p><div class="backend-actions"><button class="secondary-button" type="submit">Save server</button><button class="quiet-button" type="button" id="mcpResetBtn">New server</button></div></form></details></section>`);
document.querySelector('.composer-toolbar').insertAdjacentHTML('afterbegin', `
<div class="generation-controls"><label class="sr-only" for="chatModelSelect">Chat model</label><select id="chatModelSelect" title="Ollama model"><option value="">Choose a model</option></select><label class="sr-only" for="agentProfileSelect">Agent profile</label><select id="agentProfileSelect" title="Agent profile"></select><label class="sr-only" for="chatModeSelect">Interaction mode</label><select id="chatModeSelect" title="Chat can inspect project files; Agent can request edits"><option value="ask">Chat</option><option value="agent">Agent</option><option value="plan">Plan</option></select><button id="ragComposerToggle" type="button" class="rag-chip" aria-pressed="false" title="Include retrieved project context">RAG</button></div><button id="stopRunBtn" type="button" class="stop-button" aria-label="Stop response" hidden>Stop</button>`);
document.querySelector('.composer-wrap').insertAdjacentHTML('afterbegin', '<div id="runStatus" class="run-status" role="status" hidden></div><section id="approvalCard" class="approval-card" aria-label="Tool approval" hidden></section>');
document.getElementById('composerInput').setAttribute('maxlength', '200000');
document.getElementById('settingsSaveState').textContent = 'Appearance saves automatically. Use Save for backend settings.';
