import './extras-markup.mjs';
import {KNOWLEDGE_KEY,COOKBOOK_KEY,normalizeKnowledge,normalizeCookbook,buildContext,serializeChat,memoryCandidates,parseSkill,duplicateMemoryIds,validEndpoint,launchCommand,downloadCommand} from './workspace-data.mjs';

export function installExtras(host) {
 const {state,$,$$,el,icon,native,desktop,toast,readJSON,store,currentChat,rootPath,composer,saveDraft,saveChats,sizeComposer,showChat,renderChats,renderConversation,selectChat,ask,showDialog,isTemporary}=host;
 let library=normalizeKnowledge(readJSON(KNOWLEDGE_KEY,{})),book=normalizeCookbook(readJSON(COOKBOOK_KEY,{}));
 let editMemoryId='',editSkillId='',editRecipeId='',chatTarget=null,compactTarget=null,imports=[],importProject='';
 let modelRoot='',models=[],platform='',scanning=false;
 const clone=v=>structuredClone(v),uid=()=>crypto.randomUUID(),nameOf=p=>String(p||'').split(/[\\/]/).filter(Boolean).pop()||'Global';
 const guard=fn=>async e=>{try{await fn(e);}catch(error){toast(error.message||'The operation failed.');}};
 const menu=$('#chatMenu');
 function btn(symbol,label,action,cls='icon-button') {const b=el('button',cls);b.type='button';b.title=label;b.setAttribute('aria-label',label);b.append(icon(symbol));if(cls!=='icon-button')b.append(el('span','',label));b.addEventListener('click',guard(action));return b;}
 const size=n=>n==null?'Size unavailable':n<1048576?(n/1024).toFixed(1)+' KB':n<1073741824?(n/1048576).toFixed(1)+' MB':(n/1073741824).toFixed(2)+' GB';
 function noTemp(){if(isTemporary())throw new Error('End the temporary chat before changing library records.');}
 function closeMenu(){if(menu.matches(':popover-open'))menu.hidePopover();}
 function positionMenu(){const r=$('#chatOptionsBtn').getBoundingClientRect();menu.style.left=Math.max(8,Math.min(r.left,innerWidth-250))+'px';menu.style.top=Math.min(r.bottom+6,Math.max(8,innerHeight-menu.offsetHeight-8))+'px';}
 function toggleMenu(){if(menu.matches(':popover-open')){closeMenu();return;}update();menu.showPopover();positionMenu();menu.querySelector('button:not(:disabled)')?.focus();}
 menu.addEventListener('toggle',()=>$('#chatOptionsBtn').setAttribute('aria-expanded',String(menu.matches(':popover-open'))));
 menu.addEventListener('keydown',e=>{const list=$$('button:not(:disabled):not([hidden])',menu),i=list.indexOf(document.activeElement);let n;if(e.key==='ArrowDown')n=(i+1)%list.length;if(e.key==='ArrowUp')n=(i-1+list.length)%list.length;if(e.key==='Home')n=0;if(e.key==='End')n=list.length-1;if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeMenu();$('#chatOptionsBtn').focus();}if(n!==undefined){e.preventDefault();list[n]?.focus();}});
 window.addEventListener('resize',()=>{if(menu.matches(':popover-open'))positionMenu();});
 function update(){
  const temp=isTemporary(),chat=currentChat();$('#temporaryBadge').hidden=!temp;$('#temporaryNotice').hidden=!temp;
  $('#temporaryButton').setAttribute('aria-pressed',String(temp));$('#temporaryButton').setAttribute('aria-label',temp?'End temporary chat':'Start temporary chat');
  $('#temporaryMenuAction > span:last-child').textContent=temp?'End temporary chat':'New temporary chat';$('#deleteChatMenu').hidden=temp;
  $$('[data-needs-chat]',menu).forEach(b=>{b.disabled=!chat;});$$('[data-needs-messages]',menu).forEach(b=>{b.disabled=!chat?.messages.length;});
  $('#draftLabel').textContent=temp?'Temporary draft':'Local draft';$('#sendBtn').title=temp?'Add to temporary chat (Enter)':'Save message locally (Enter)';$('#sendBtn').setAttribute('aria-label',temp?'Add to temporary chat':'Save message locally');
  $('#composerHint').replaceChildren();if(temp)$('#composerHint').textContent='No history or knowledge use. Local privacy, not network anonymity.';else{const b=el('button','text-button','Set up your agent backend');b.dataset.action='connection';b.append(icon('arrow-right'));$('#composerHint').append(document.createTextNode('Messages stay on this device. '),b);}
  if(temp)$('#welcomeText').textContent='A clean session. No saved history, memories, or skills.';
  $('#knowledgeTemporaryNote').hidden=!temp;$('#compactionBadge').hidden=!chat?.compaction?.summary;
  $('#memoryCount').textContent=String(library.memories.length);$('#skillCount').textContent=String(library.skills.length);
  const recipe=book.recipes.find(r=>r.id===book.activeRecipeId);$('#activeSetupButton').hidden=!recipe;$('#activeSetupButton').textContent=recipe?'Model setup: '+recipe.name:'';
  ['saveMemoryBtn','saveSkillBtn','importKnowledgeBtn','fetchSkillBtn','confirmImportBtn'].forEach(id=>{$('#'+id).disabled=temp;});
  ['memoryAddScope','skillAddScope','importScope'].forEach(id=>{$('#'+id+' option[value="project"]').disabled=!rootPath();});
 }
 async function discardTemporary(){if(!isTemporary())return true;if((state.temporary.messages.length||composer.value.trim()||state.temporaryDraft.trim())&&!await ask('End temporary chat?','This conversation and its unsent draft will be discarded, not saved to history.',undefined,'Discard session'))return false;state.temporary=null;state.temporaryDraft='';composer.value='';return true;}
 async function startTemporary(){closeMenu();if(isTemporary()){await selectChat(state.temporaryReturnId);return;}if(!saveDraft())return;state.temporaryReturnId=state.activeChatId;state.temporary={id:'temporary-'+uid(),temporary:true,title:'June chat',projectPath:rootPath(),messages:[],createdAt:Date.now(),mode:state.settings.agentMode,contextBudget:state.settings.contextBudget};state.temporaryDraft='';state.activeChatId='';composer.value='';showChat();renderChats();renderConversation();sizeComposer();composer.focus();toast('Temporary chat started. Messages and drafts are not saved.');}
 async function consentExport(){return !isTemporary()||Boolean(await ask('Keep a copy of this temporary chat?','Copying or exporting creates a copy outside temporary mode. June cannot delete that copy for you.',undefined,'Keep a copy'));}
 async function copyText(value){if(!value)throw new Error('There is nothing to copy.');if(desktop?.copyText)await native('copyText',value);else await navigator.clipboard.writeText(value);toast('Copied.');}
 async function saveArtifact(payload){if(desktop?.saveArtifact)return native('saveArtifact',payload);if(payload.format==='pdf')throw new Error('PDF export requires the updated desktop app. Restart after updating.');const url=URL.createObjectURL(new Blob([payload.text],{type:payload.format==='json'?'application/json':'text/markdown;charset=utf-8'})),a=el('a');a.href=url;a.download=payload.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);return {saved:true};}
 async function exportChat(format,documents=false){const chat=currentChat();if(!chat?.messages.length||!await consentExport())return;const result=await saveArtifact({format,name:(chat.title||'June chat').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,80)+'.'+format,title:chat.title||'June chat',text:serializeChat(chat),documents});if(result?.saved)toast('Chat exported.');}
 function ensureChat(){if(currentChat())return currentChat();const chat={id:uid(),title:'June chat',projectPath:rootPath(),messages:[],createdAt:Date.now(),updatedAt:Date.now(),mode:state.settings.agentMode,contextBudget:state.settings.contextBudget};state.chats.push(chat);if(!saveChats()){state.chats.pop();throw new Error('Chat could not be saved.');}state.activeChatId=chat.id;state.drafts[chat.id]=composer.value;state.drafts['new:'+rootPath()]='';store('june.activeChatId',chat.id);store('june.drafts',state.drafts);return chat;}
 function openChatSettings(){chatTarget=currentChat();$('#chatMode').value=chatTarget?.mode||state.settings.agentMode;$('#chatBudget').value=chatTarget?.contextBudget||state.settings.contextBudget;showDialog('chatSettingsDialog');}
 $('#chatSettingsForm').addEventListener('submit',guard(e=>{e.preventDefault();const budget=Number($('#chatBudget').value);if(!Number.isInteger(budget)||budget<1024||budget>2097152)throw new Error('Invalid context budget.');const chat=chatTarget||ensureChat(),previous={mode:chat.mode,contextBudget:chat.contextBudget};chat.mode=$('#chatMode').value;chat.contextBudget=budget;if(!chat.temporary&&!saveChats()){Object.assign(chat,previous);return;}$('#chatSettingsDialog').close();renderChats();renderConversation();toast('Chat settings saved.');}));
 function openCompact(){compactTarget=currentChat();if(!compactTarget?.messages.length)return;$('#compactSummary').value=compactTarget.compaction?.summary||'';$('#compactKeep').value=Math.min(compactTarget.messages.length,6);$('#compactStatus').textContent=compactTarget.messages.length+' messages. Full history will remain unchanged.';showDialog('compactDialog');}
 $('#compactForm').addEventListener('submit',guard(e=>{e.preventDefault();const chat=compactTarget,keep=Number($('#compactKeep').value),summary=$('#compactSummary').value.trim();if(!chat||!summary||!Number.isInteger(keep)||keep<0||keep>100)throw new Error('Enter a summary and recent message count.');const old=chat.compaction;chat.compaction={summary,through:Math.max(0,chat.messages.length-keep),createdAt:Date.now()};if(!chat.temporary&&!saveChats()){chat.compaction=old;return;}$('#compactDialog').close();update();toast('Summary saved. History unchanged.');}));
 function saveLibrary(next){next=normalizeKnowledge(next);if(!store(KNOWLEDGE_KEY,next))throw new Error('Library could not be saved.');library=next;renderLibrary();$('#knowledgeStatus').textContent='Saved on this device.';}
 function scoped(item,scope){return scope==='all'||(scope==='global'?!item.projectPath:scope==='project'?Boolean(rootPath())&&item.projectPath===rootPath():!item.projectPath||item.projectPath===rootPath());}
 function selectedScope(id,original){const v=$('#'+id).value;if(v==='original')return original?.projectPath||'';if(v==='project'){if(!rootPath())throw new Error('Select a project first.');return rootPath();}return '';}
 function setScope(id,item){const select=$('#'+id);select.querySelector('[value="original"]')?.remove();if(item?.projectPath&&item.projectPath!==rootPath()){const o=el('option','',nameOf(item.projectPath)+' (original)');o.value='original';select.append(o);select.value='original';}else select.value=item?(item.projectPath?'project':'global'):rootPath()?'project':'global';}
 function libraryTab(tab){$$('[data-knowledge-tab]').forEach(b=>{const on=b.dataset.knowledgeTab===tab;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;$('#knowledge-'+b.dataset.knowledgeTab+'-page').hidden=!on;});$('#knowledgeDialog > .feature-body').scrollTop=0;}
 function resetEditors(){editMemoryId='';editSkillId='';$('#memoryForm').reset();$('#skillForm').reset();$('#memoryFormHeading').textContent='Add a memory';$('#skillFormHeading').textContent='Add a skill';$('#saveMemoryBtn').textContent='Add memory';$('#saveSkillBtn').textContent='Add skill';$('#cancelMemoryEdit').hidden=$('#cancelSkillEdit').hidden=true;setScope('memoryAddScope');setScope('skillAddScope');}
 function openKnowledge(tab='memories'){if(tab==='add'&&!editMemoryId&&!editSkillId)resetEditors();renderLibrary();libraryTab(tab);showDialog('knowledgeDialog');}
 function emptyList(list,title,description){const box=el('div','library-empty');box.append(icon('brain'),el('h3','',title),el('p','',description));if(!isTemporary())box.append(btn('plus','Add an entry',()=>openKnowledge('add'),'secondary-button'));list.append(box);}
 function entrySwitch(value,label,fn){const i=el('input','switch-control');i.type='checkbox';i.checked=value;i.setAttribute('role','switch');i.setAttribute('aria-label',label);i.disabled=isTemporary();i.addEventListener('change',guard(fn));return i;}
 function renderLibrary(){
  $('#memoriesEnabled').checked=library.preferences.memoriesEnabled;$('#skillsEnabled').checked=library.preferences.skillsEnabled;$('#maxSkills').value=library.preferences.maxSkills;
  const ml=$('#memoryList'),sl=$('#skillList');ml.replaceChildren();sl.replaceChildren();
  const q=$('#memorySearch').value.trim().toLowerCase(),memories=library.memories.filter(m=>scoped(m,$('#memoryScope').value)&&m.content.toLowerCase().includes(q));
  memories.sort($('#memorySort').value==='alpha'?(a,b)=>a.content.localeCompare(b.content):$('#memorySort').value==='oldest'?(a,b)=>a.createdAt-b.createdAt:(a,b)=>b.createdAt-a.createdAt);
  for(const m of memories){const card=el('article','knowledge-entry'),h=el('div','entry-head'),tags=el('div','entry-labels');tags.append(el('span','tag',m.category),el('span','scope-tag',m.projectPath?nameOf(m.projectPath):'Global'));h.append(tags,entrySwitch(m.enabled,'Enable memory',e=>{noTemp();const next=clone(library);next.memories.find(i=>i.id===m.id).enabled=e.target.checked;saveLibrary(next);}));const actions=el('div','entry-actions'),edit=btn('edit','Edit memory',()=>editMemory(m)),del=btn('trash','Delete memory',()=>removeEntry('memories',m));edit.disabled=del.disabled=isTemporary();actions.append(edit,del);card.append(h,el('p','entry-content',m.content),actions);ml.append(card);}
  if(!memories.length)emptyList(ml,library.memories.length?'No matching memories':'No memories yet','Keep useful facts and preferences here.');
  const sq=$('#skillSearch').value.trim().toLowerCase(),skills=library.skills.filter(s=>scoped(s,$('#skillScope').value)&&[s.title,s.when,s.tags.join(' ')].join(' ').toLowerCase().includes(sq));
  for(const s of skills){const card=el('article','knowledge-entry'),h=el('div','entry-head'),labels=el('div','entry-labels');labels.append(el('strong','',s.title),el('span','tag',s.approved?'Approved':'Draft'));h.append(labels,entrySwitch(s.enabled,'Enable skill',e=>{noTemp();const next=clone(library);next.skills.find(i=>i.id===s.id).enabled=e.target.checked;saveLibrary(next);}));const details=el('details','skill-instructions');details.append(el('summary','','Instructions'),el('pre','',s.how));const actions=el('div','entry-actions');actions.append(el('span','scope-tag',s.projectPath?nameOf(s.projectPath):'Global'));if(!s.approved){const b=btn('check','Review & approve',()=>{editSkill(s);$('#skillApprove').focus();},'quiet-button');b.disabled=isTemporary();actions.append(b);}const edit=btn('edit','Edit skill',()=>editSkill(s)),del=btn('trash','Delete skill',()=>removeEntry('skills',s));edit.disabled=del.disabled=isTemporary();actions.append(edit,del);card.append(h,el('p','entry-content',s.when),el('p','entry-tags',s.tags.join(' / ')),details,actions);sl.append(card);}
  if(!skills.length)emptyList(sl,library.skills.length?'No matching skills':'No skills yet','Store procedures you can review and reuse.');update();
 }
 function editMemory(m){noTemp();editMemoryId=m.id;$('#memoryContent').value=m.content;$('#memoryCategory').value=m.category;setScope('memoryAddScope',m);$('#memoryFormHeading').textContent='Edit memory';$('#saveMemoryBtn').textContent='Save memory';$('#cancelMemoryEdit').hidden=false;openKnowledge('add');$('#memoryContent').focus();}
 function editSkill(s){noTemp();editSkillId=s.id;$('#skillTitle').value=s.title;$('#skillWhen').value=s.when;$('#skillHow').value=s.how;$('#skillTags').value=s.tags.join(', ');$('#skillApprove').checked=s.approved;setScope('skillAddScope',s);$('#skillFormHeading').textContent='Edit skill';$('#saveSkillBtn').textContent='Save skill';$('#cancelSkillEdit').hidden=false;openKnowledge('add');}
 async function removeEntry(kind,item){noTemp();if(!await ask(kind==='skills'?'Delete skill?':'Delete memory?','Remove this record from your local library?',undefined,'Delete'))return;const next=clone(library);next[kind]=next[kind].filter(i=>i.id!==item.id);saveLibrary(next);}
 $('#memoryForm').addEventListener('submit',guard(e=>{e.preventDefault();noTemp();const original=library.memories.find(m=>m.id===editMemoryId),content=$('#memoryContent').value.trim();if(!content)throw new Error('Enter a memory.');if(!original&&library.memories.length>=1000)throw new Error('Memory limit reached (1,000).');const item={id:original?.id||uid(),content,category:$('#memoryCategory').value,projectPath:selectedScope('memoryAddScope',original),enabled:original?.enabled!==false,createdAt:original?.createdAt||Date.now(),updatedAt:Date.now()},next=clone(library);next.memories=next.memories.filter(m=>m.id!==item.id);next.memories.unshift(item);saveLibrary(next);resetEditors();libraryTab('memories');}));
 $('#skillForm').addEventListener('submit',guard(e=>{e.preventDefault();noTemp();const original=library.skills.find(s=>s.id===editSkillId);if(!original&&library.skills.length>=500)throw new Error('Skill limit reached (500).');const item={id:original?.id||uid(),title:$('#skillTitle').value.trim(),when:$('#skillWhen').value.trim(),how:$('#skillHow').value.trim(),tags:$('#skillTags').value.split(',').map(s=>s.trim()).filter(Boolean).slice(0,20),approved:$('#skillApprove').checked,enabled:original?.enabled!==false,source:original?.source||'Manual',projectPath:selectedScope('skillAddScope',original),createdAt:original?.createdAt||Date.now(),updatedAt:Date.now()};if(!item.title||!item.when||!item.how)throw new Error('Complete the title, when to use and instructions.');const next=clone(library);next.skills=next.skills.filter(s=>s.id!==item.id);next.skills.unshift(item);saveLibrary(next);resetEditors();libraryTab('skills');}));
 for(const id of ['memoriesEnabled','skillsEnabled','maxSkills'])$('#'+id).addEventListener('change',guard(e=>{const v=e.target.type==='checkbox'?e.target.checked:Number(e.target.value);if(id==='maxSkills'&&(!Number.isInteger(v)||v<0||v>20))throw new Error('Choose 0 to 20 skills.');const next=clone(library);next.preferences[id]=v;saveLibrary(next);}));
 for(const id of ['memorySearch','skillSearch'])$('#'+id).addEventListener('input',renderLibrary);
 for(const id of ['memoryScope','skillScope','memorySort'])$('#'+id).addEventListener('change',renderLibrary);
 $$('[data-knowledge-tab]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.knowledgeTab==='add'&&!editMemoryId&&!editSkillId)resetEditors();libraryTab(b.dataset.knowledgeTab);}));
 async function exportKnowledge(){const r=await saveArtifact({format:'json',name:'june-knowledge.json',title:'June knowledge',text:JSON.stringify(library,null,2)});if(r?.saved)toast('Knowledge library exported.');}
 function reviewImport(items){noTemp();if(!items.length)throw new Error('No supported entries were found.');imports=items;importProject=rootPath();$('#importScope').value=importProject?'project':'global';const list=$('#importCandidates');list.replaceChildren();items.forEach((item,index)=>{const row=el('label','import-candidate'),c=el('input');c.type='checkbox';c.checked=true;c.dataset.candidate=String(index);const body=el('div');body.append(el('strong','',item.kind==='skill'?item.title:'Memory'),el('p','',item.kind==='skill'?item.when:item.content));row.append(c,body);list.append(row);});showDialog('importReviewDialog');}
 $('#knowledgeFileInput').addEventListener('change',guard(async e=>{noTemp();const f=e.target.files[0];e.target.value='';if(!f)return;if(f.size>1048576)throw new Error('Choose a file no larger than 1 MB.');const text=await f.text();reviewImport(/^SKILL\.md$/i.test(f.name)?[parseSkill(text,f.name)]:memoryCandidates(text,f.name));$('#importStatus').textContent='Review up to 100 proposed entries before saving.';}));
 $('#skillUrlForm').addEventListener('submit',guard(async e=>{e.preventDefault();noTemp();$('#fetchSkillBtn').disabled=true;$('#importStatus').textContent='Fetching text only...';try{const result=await native('fetchSkill',$('#skillImportUrl').value);noTemp();reviewImport([parseSkill(result.content,result.source)]);$('#importStatus').textContent='Fetched. Review before saving.';}catch(error){$('#importStatus').textContent=error.message;throw error;}finally{$('#fetchSkillBtn').disabled=isTemporary();}}));
 $('#importReviewDialog').addEventListener('close',()=>{imports=[];$('#importCandidates').replaceChildren();});
 function confirmImport(){noTemp();const selected=$$('[data-candidate]:checked').map(i=>imports[Number(i.dataset.candidate)]).filter(Boolean);if(!selected.length)throw new Error('Select at least one item.');const scope=$('#importScope').value==='project'?importProject:'';if($('#importScope').value==='project'&&!scope)throw new Error('No project selected.');const next=clone(library);if(next.memories.length+selected.filter(i=>i.kind==='memory').length>1000||next.skills.length+selected.filter(i=>i.kind==='skill').length>500)throw new Error('Import exceeds library limits. Select fewer entries.');for(const item of selected){const entry={...item,id:uid(),projectPath:scope,enabled:true,createdAt:Date.now(),updatedAt:Date.now()};delete entry.kind;if(item.kind==='skill'){entry.approved=false;next.skills.unshift(entry);}else next.memories.unshift(entry);}saveLibrary(next);$('#importReviewDialog').close();libraryTab(selected.some(i=>i.kind==='skill')?'skills':'memories');toast(selected.length+' entries imported. Skills are unapproved drafts.');}
 async function tidyMemories(){noTemp();const ids=duplicateMemoryIds(library.memories);if(!ids.length){toast('No exact duplicates found.');return;}if(!await ask('Remove exact duplicates?',ids.length+' duplicate memories found in the same category and scope. One copy of each is kept. This is not an AI rewrite.',undefined,'Remove duplicates'))return;const next=clone(library);next.memories=next.memories.filter(m=>!ids.includes(m.id));saveLibrary(next);}
 function saveBook(next){next=normalizeCookbook(next);if(!store(COOKBOOK_KEY,next))throw new Error('Cookbook could not be saved.');book=next;renderRecipes();update();$('#cookbookStatus').textContent='Saved on this device.';}
 function bookTab(tab){$$('[data-cookbook-tab]').forEach(b=>{const on=b.dataset.cookbookTab===tab;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;$('#cookbook-'+b.dataset.cookbookTab+'-page').hidden=!on;});$('#cookbookDialog > .feature-body').scrollTop=0;}
 function shellLabels(){$$('.shell-label').forEach(n=>{n.textContent=platform==='win32'?'(PowerShell)':'(POSIX shell)';});}
 async function openCookbook(tab='launch'){renderRecipes();bookTab(tab);$('#cookbookRuntime').value=book.preferences.runtime;$('#cookbookEndpoint').value=book.preferences.endpoint;$('#cookbookContext').value=book.preferences.context;showDialog('cookbookDialog');if(desktop?.getCookbookInfo){try{const info=await native('getCookbookInfo');modelRoot=info.modelRoot||'';platform=info.platform||platform;$('#modelFolderPath').textContent=modelRoot||'No folder selected.';$('#scanModelsBtn').disabled=!modelRoot;shellLabels();}catch(e){$('#modelScanStatus').textContent=e.message;}}else{$('#modelScanStatus').textContent='Local discovery requires the updated desktop app. Saved setups work in web preview.';$('#scanModelsBtn').disabled=true;}renderModels();}
 function renderRecipes(){const list=$('#recipeList');list.replaceChildren();for(const r of book.recipes){const card=el('article','recipe-entry'),body=el('div');body.append(el('strong','',r.name),el('small','',r.runtime+' / '+r.model+' / '+r.context.toLocaleString()+' ctx'));const use=btn('check',r.id===book.activeRecipeId?'Selected':'Use setup',()=>useRecipe(r),'secondary-button');use.disabled=r.id===book.activeRecipeId;card.append(icon('cpu'),body,use,btn('edit','Edit setup',()=>openRecipe(r)),btn('trash','Delete setup',()=>deleteRecipe(r)));list.append(card);}if(!book.recipes.length)list.append(el('p','tree-notice','No saved setups. Add one, or select a model below.'));}
 function useRecipe(r){const nextSettings={...state.settings,defaultModel:r.model,contextBudget:r.context};if(!store('june.settings',nextSettings))return;state.settings=nextSettings;host.syncSettings();const next=clone(book);next.activeRecipeId=r.id;saveBook(next);toast('Model preference selected. No server was started.');}
 async function deleteRecipe(r){if(!await ask('Delete model setup?','Only the configuration is removed. No model files are deleted.',undefined,'Delete setup'))return;const next=clone(book);next.recipes=next.recipes.filter(i=>i.id!==r.id);if(next.activeRecipeId===r.id)next.activeRecipeId='';saveBook(next);}
 function recipeForm(){return {id:editRecipeId||uid(),name:$('#recipeName').value.trim(),model:$('#recipeModel').value.trim(),runtime:$('#recipeRuntime').value,filePath:$('#recipePath').value.trim(),endpoint:$('#recipeEndpoint').value.trim(),context:Number($('#recipeContext').value)};}
 function updateCommand(){try{$('#recipeCommand').value=launchCommand(recipeForm(),platform);}catch{$('#recipeCommand').value='Complete a valid model path and endpoint to prepare the command.';}}
 function openRecipe(r=null,m=null){editRecipeId=r?.id||'';$('#recipeName').value=r?.name||m?.name||'';$('#recipeModel').value=r?.model||m?.modelId||m?.name||'';$('#recipePath').value=r?.filePath||(m?.format==='gguf'?m.path:'')||'';$('#recipeRuntime').value=r?.runtime||(m?.format==='huggingface'?'custom':book.preferences.runtime);$('#recipeEndpoint').value=r?.endpoint||book.preferences.endpoint;$('#recipeContext').value=r?.context||book.preferences.context;updateCommand();shellLabels();showDialog('recipeDialog');}
 $('#recipeForm').addEventListener('input',updateCommand);
 $('#recipeForm').addEventListener('submit',guard(e=>{e.preventDefault();const r=recipeForm();if(!r.name||!r.model||!validEndpoint(r.endpoint)||!Number.isInteger(r.context)||r.context<1024||r.context>2097152)throw new Error('Enter valid setup details.');if(!editRecipeId&&book.recipes.length>=200)throw new Error('Setup limit reached (200).');const next=clone(book);next.recipes=next.recipes.filter(i=>i.id!==r.id);next.recipes.unshift(r);saveBook(next);$('#recipeDialog').close();}));
 $('#cookbookPreferencesForm').addEventListener('submit',guard(e=>{e.preventDefault();const endpoint=$('#cookbookEndpoint').value.trim(),context=Number($('#cookbookContext').value);if(!validEndpoint(endpoint)||!Number.isInteger(context)||context<1024||context>2097152)throw new Error('Enter a valid endpoint and context budget.');const next=clone(book);next.preferences={runtime:$('#cookbookRuntime').value,endpoint,context};saveBook(next);toast('Defaults saved.');}));
 function renderModels(){const list=$('#localModelList');list.replaceChildren();const filter=$('#modelTypeFilter').value,q=$('#modelSearch').value.trim().toLowerCase(),matches=models.filter(m=>(filter==='all'||m.format===filter)&&(m.name+' '+m.path).toLowerCase().includes(q));for(const m of matches){const row=el('article','model-entry'),body=el('div');body.append(el('strong','',m.name),el('small','',(m.format==='gguf'?'GGUF':'HF cache')+' / '+size(m.size)+' / '+m.path));row.append(icon('cpu'),body,btn('plus','Set up',()=>openRecipe(null,m),'quiet-button'));list.append(row);}if(!matches.length)list.append(el('p','tree-notice',models.length?'No matching models.':modelRoot?'Scan this folder to discover local model metadata.':'Choose a model or Hugging Face cache folder.'));}
 async function scanModels(){if(scanning)return;scanning=true;$('#scanModelsBtn').disabled=$('#chooseModelsBtn').disabled=true;$('#modelScanStatus').textContent='Scanning filenames and metadata, not model weights...';try{const r=await native('scanModels');models=r.models;$('#modelScanStatus').textContent=models.length+' models found.'+(r.truncated?' Scan limit reached; choose a narrower folder.':'')+(r.skipped?' Some paths were inaccessible or outside the selected folder.':'');renderModels();}catch(e){$('#modelScanStatus').textContent=e.message;throw e;}finally{scanning=false;$('#scanModelsBtn').disabled=!modelRoot;$('#chooseModelsBtn').disabled=false;}}
 async function chooseModels(){const r=await native('chooseModelFolder');if(!r)return;modelRoot=r.path;models=[];$('#modelFolderPath').textContent=modelRoot;$('#scanModelsBtn').disabled=false;await scanModels();}
 async function inspect(){const b=$('#checkDepsBtn');b.disabled=true;$('#dependencyStatus').textContent='Checking fixed version commands and system information...';try{const r=await native('inspectEnvironment'),hw=$('#hardwareInfo');hw.hidden=false;hw.replaceChildren(el('h3','','This device'),el('p','',r.cpu+' / '+r.logicalCpus+' logical CPUs'),el('p','',size(r.ram)+' RAM / '+size(r.freeRam)+' currently free'),el('p','settings-note','GPU memory and inference speed are not estimated.'));const list=$('#dependencyList');list.replaceChildren();for(const d of r.dependencies){const row=el('div','dependency-row');row.append(el('strong','',d.name),el('span',d.available?'dependency-ok':'',d.available?d.version:d.reason||'Not detected'));list.append(row);}$('#dependencyStatus').textContent='Checks finished. Nothing installed or changed.';}catch(e){$('#dependencyStatus').textContent=e.message;throw e;}finally{b.disabled=false;}}
 $('#downloadForm').addEventListener('submit',guard(e=>{e.preventDefault();$('#downloadCommand').value=downloadCommand($('#downloadRepo').value.trim(),$('#downloadFile').value.trim(),platform);}));
 $('#downloadForm').addEventListener('input',()=>{$('#downloadCommand').value='';});$('#modelSearch').addEventListener('input',renderModels);$('#modelTypeFilter').addEventListener('change',renderModels);
 $$('[data-cookbook-tab]').forEach(b=>b.addEventListener('click',()=>bookTab(b.dataset.cookbookTab)));
 const actions={temporary:startTemporary,'end-temporary':()=>selectChat(state.temporaryReturnId),memories:()=>openKnowledge('memories'),skills:()=>openKnowledge('skills'),cookbook:()=>openCookbook(),'chat-settings':openChatSettings,compact:openCompact,
  'copy-chat':async()=>{const c=currentChat();if(c?.messages.length&&await consentExport())await copyText(serializeChat(c));},'export-md':()=>exportChat('md'),'export-pdf':()=>exportChat('pdf'),'save-document':()=>exportChat('md',true),
  'clear-compaction':()=>{if(!compactTarget)return;const old=compactTarget.compaction;delete compactTarget.compaction;if(!compactTarget.temporary&&!saveChats()){compactTarget.compaction=old;return;}$('#compactDialog').close();update();},
  'import-knowledge':()=>{noTemp();$('#knowledgeFileInput').click();},'export-knowledge':exportKnowledge,'confirm-import':confirmImport,'cancel-edit':resetEditors,'tidy-memories':tidyMemories,
  'add-recipe':()=>openRecipe(),'choose-models':chooseModels,'scan-models':scanModels,'check-dependencies':inspect,'copy-launch':()=>copyText(launchCommand(recipeForm(),platform)),'copy-download':()=>copyText($('#downloadCommand').value),
  'open-model-page':()=>{const repo=$('#downloadRepo').value.trim();downloadCommand(repo,$('#downloadFile').value.trim(),platform);return native('openModelPage',repo);}};
 document.addEventListener('click',guard(async e=>{const b=e.target.closest('[data-extra]');if(b&&!b.disabled){closeMenu();await actions[b.dataset.extra]?.();}if(e.target.closest('#chatMenu [data-action]'))closeMenu();}));
 resetEditors();update();
 return {update,closeMenu,toggleMenu,menuOpen:()=>menu.matches(':popover-open'),startTemporary,discardTemporary,openKnowledge,openCookbook,requestContext:()=>({...buildContext(currentChat(),library,rootPath(),isTemporary()),modelSetup:book.recipes.find(r=>r.id===book.activeRecipeId)||null})};
}
