/* Static trusted UI templates. User data is inserted separately with textContent. */
const ico = name => `<span data-icon="${name}"></span>`;
const button = (label, action, symbol='', attrs='') => `<button type="button" class="secondary-button" data-extra="${action}" ${attrs}>${symbol?ico(symbol):''}${label}</button>`;
const options = pairs => pairs.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');
const select = (id,pairs) => `<select id="${id}">${options(pairs)}</select>`;
const input = (id,type='text',attrs='')=>`<input id="${id}" type="${type}" ${attrs}>`;
const field = (label,html)=>`<label class="stacked-setting">${label}${html}</label>`;
const note = text=>`<p class="settings-note">${text}</p>`;
const scope = id=>select(id,[['global','Global'],['project','This project']]);
const scopeFilter = id=>select(id,[['applicable','Global + this project'],['global','Global only'],['project','This project only'],['all','All projects']]);
const runtime = id=>select(id,[['llama.cpp','llama.cpp'],['ollama','Ollama'],['custom','Custom backend']]);
const submit = (label,id='')=>`<button type="submit" class="primary-button" ${id?`id="${id}"`:''}>${label}</button>`;
const dialog = (id,title,body,classes='',footer='')=>`<dialog id="${id}" class="feature-dialog ${classes}" aria-labelledby="${id}Title"><header class="dialog-header"><h2 id="${id}Title">${title}</h2><button type="button" class="icon-button" data-close="${id}" aria-label="Close ${title.replace(/<[^>]+>/g,'')}">${ico('x')}</button></header>${body}${footer?`<footer class="dialog-footer">${footer}</footer>`:''}</dialog>`;
const tabs=(kind,entries)=>`<nav class="feature-tabs" role="tablist" aria-label="${kind} tabs">${entries.map(([id,name,symbol],i)=>`<button id="${kind}-${id}-tab" role="tab" data-${kind}-tab="${id}" aria-selected="${i===0}" aria-controls="${kind}-${id}-page" tabindex="${i===0?0:-1}">${ico(symbol)}${name}</button>`).join('')}</nav>`;
const page=(kind,id,body,hidden=false)=>`<section id="${kind}-${id}-page" role="tabpanel" aria-labelledby="${kind}-${id}-tab" ${hidden?'hidden':''}>${body}</section>`;
const enabled = id=>`<label class="switch-label">Enabled<input id="${id}" type="checkbox" class="switch-control" role="switch" checked></label>`;
const head=(title,description,action='')=>`<div class="feature-section-head"><div><h3>${title}</h3><p>${description}</p></div>${action}</div>`;
const search=(id,placeholder)=>`<label class="search-field">${ico('search')}<input id="${id}" type="search" aria-label="${placeholder}" placeholder="${placeholder}"></label>`;
export const extraMarkup = `
<div id="chatMenu" class="chat-menu" popover="auto" role="menu" aria-label="June chat actions">
 <button role="menuitem" data-action="rename-chat" data-needs-chat>${ico('edit')}Rename</button>
 <button role="menuitem" data-extra="compact" data-needs-messages>${ico('compress')}Compact context</button>
 <button role="menuitem" data-extra="copy-chat" data-needs-messages>${ico('copy')}Copy chat</button>
 <button role="menuitem" data-extra="export-md" data-needs-messages>${ico('file')}Export Markdown</button>
 <button role="menuitem" data-extra="export-pdf" data-needs-messages>${ico('download')}Export PDF</button>
 <button role="menuitem" data-extra="save-document" data-needs-messages>${ico('folder-plus')}Save to Documents</button><div role="separator"></div>
 <button role="menuitem" data-extra="chat-settings">${ico('settings')}Chat settings</button>
 <button role="menuitem" data-extra="memories">${ico('brain')}Memories &amp; skills</button>
 <button role="menuitem" data-extra="temporary" id="temporaryMenuAction">${ico('shield')}<span>New temporary chat</span></button><div role="separator"></div>
 <button role="menuitem" data-action="delete-chat" data-needs-chat class="danger-text" id="deleteChatMenu">${ico('trash')}Delete chat</button>
</div>
${dialog('chatSettingsDialog','Chat settings',`<form id="chatSettingsForm" class="feature-body">${note('Overrides for this conversation. Your global defaults are unchanged.')}${field('Mode',select('chatMode',[['agent','Agent'],['ask','Chat'],['plan','Plan']]))}${field('Context budget',input('chatBudget','number','min="1024" max="2097152" required'))}${note('Applied to Ollama requests. The global context limit is the upper bound. Temporary chats exclude memories, skills, RAG, and MCP.')}${submit('Save')}</form>`,'small-dialog')}
${dialog('compactDialog','Compact context',`<form id="compactForm" class="feature-body">${note('Generate a draft with the instructions in Settings → General, or write your own summary. Review it before saving. Full message history stays intact.')}${field('Summary','<textarea id="compactSummary" rows="7" maxlength="16000" required></textarea>')}${field('Keep recent messages',input('compactKeep','number','min="0" max="100" value="6" required'))}<p id="compactStatus" class="settings-note" role="status"></p><div class="library-actions">${button('Generate draft','generate-compaction','','id="generateCompactBtn"')}${button('Stop','cancel-compaction','','id="cancelCompactBtn" hidden')}${button('Clear summary','clear-compaction')}${submit('Save summary')}</div></form>`,'small-dialog')}
${dialog('knowledgeDialog',`${ico('brain')}Memories &amp; skills`,tabs('knowledge',[['memories','Memories <span id="memoryCount" class="count">0</span>','brain'],['skills','Skills <span id="skillCount" class="count">0</span>','bolt'],['add','Add','plus'],['settings','Settings','settings']])+`<div class="feature-body"><p id="knowledgeTemporaryNote" class="notice-banner" hidden>Temporary chat: the library is excluded. End this chat before adding, importing, or changing records.</p>`+
page('knowledge','memories',head('Things worth remembering','Facts and preferences you choose to keep.',enabled('memoriesEnabled'))+`<div class="library-toolbar">${search('memorySearch','Search memories')}${scopeFilter('memoryScope')}</div><div class="library-actions">${select('memorySort',[['newest','Newest first'],['oldest','Oldest first'],['alpha','Alphabetical']])}${button('Find duplicates','tidy-memories','compress')}${button('Export','export-knowledge','download')}</div><div id="memoryList" class="library-list"></div>`)+
page('knowledge','skills',head('Reusable instructions','Review a skill before making it available to your agent.',enabled('skillsEnabled'))+`<div class="library-toolbar">${search('skillSearch','Search skills or tags')}${scopeFilter('skillScope')}</div><div id="skillList" class="library-list"></div>`,true)+
page('knowledge','add',`<section class="feature-card"><h3 id="memoryFormHeading">Add a memory</h3><form id="memoryForm">${field('Memory','<textarea id="memoryContent" rows="3" maxlength="8000" required placeholder="Use pytest and keep public APIs backwards compatible."></textarea>')}<div class="form-row">${field('Category',select('memoryCategory',[['fact','Fact'],['preference','Preference'],['project','Project detail'],['instruction','Instruction']]))}${field('Scope',scope('memoryAddScope'))}${submit('Add memory','saveMemoryBtn')}${button('Cancel edit','cancel-edit','','id="cancelMemoryEdit" hidden')}</div></form></section>
<section class="feature-card"><h3 id="skillFormHeading">Add a skill</h3><form id="skillForm">${field('Title',input('skillTitle','text','maxlength="120" required'))}${field('When to use',input('skillWhen','text','maxlength="4000" required'))}${field('Instructions','<textarea id="skillHow" rows="5" maxlength="30000" required></textarea>')}<div class="form-row">${field('Tags',input('skillTags','text','maxlength="500" placeholder="python, review, tests"'))}${field('Scope',scope('skillAddScope'))}</div><label class="inline-check"><input id="skillApprove" type="checkbox">I have reviewed and approve these instructions.</label><div class="library-actions">${submit('Add skill','saveSkillBtn')}${button('Cancel edit','cancel-edit','','id="cancelSkillEdit" hidden')}</div></form></section>
<section class="feature-card"><h3>Import for review</h3>${note('Text/Markdown paragraphs become proposed memories, not AI-extracted facts. June JSON backups and SKILL.md files are supported. Imports never execute code.')}<div class="library-actions">${button('Choose file','import-knowledge','upload','id="importKnowledgeBtn"')}${button('Export library','export-knowledge','download')}</div><input id="knowledgeFileInput" type="file" accept=".txt,.md,.json" hidden><form id="skillUrlForm">${field('GitHub SKILL.md URL','<div class="input-action">'+input('skillImportUrl','url','required placeholder="https://github.com/owner/repo/blob/main/SKILL.md"')+submit('Fetch for review','fetchSkillBtn')+'</div>')}</form><p id="importStatus" class="settings-note" role="status"></p></section>`,true)+
page('knowledge','settings',`<h3>Knowledge in agent requests</h3>${note('Only enabled memories and approved, enabled skills are eligible. Project entries are never used in other projects. Temporary chats exclude both.')}${field('Maximum skills per request (0 disables)',input('maxSkills','number','min="0" max="20" value="3"'))}<section class="feature-card"><h3>Automatic extraction and audits</h3>${note('Manual add, edit, import, export, and approval work now. Extraction, confidence scores, and automatic skill audits require the agent backend and are not running.')}</section>${note('The library is local and not encrypted. Do not save passwords or API keys here.')}`,true)+`</div>`,'library-dialog','<span id="knowledgeStatus" role="status">Local library. Nothing is sent automatically.</span><button class="secondary-button" data-close="knowledgeDialog">Done</button>')}
${dialog('importReviewDialog','Review imported knowledge',`<div class="feature-body">${note('Only selected items will be saved. Imported skills remain drafts until separately approved.')}${field('Import scope',scope('importScope'))}<div id="importCandidates" class="library-list"></div></div>`,'review-dialog',`<button class="secondary-button" data-close="importReviewDialog">Cancel</button>${button('Import selected','confirm-import','','id="confirmImportBtn"')}`)}
${dialog('cookbookDialog',`${ico('book')}Cookbook`,tabs('cookbook',[['launch','Launch','play'],['download','Download','download'],['dependencies','Dependencies','cpu'],['settings','Settings','settings']])+`<div class="feature-body">`+
page('cookbook','launch',head('Model setups','Choose a setup for your pipeline, or prepare one from a local model.',button('Add setup','add-recipe','plus'))+`<div id="recipeList" class="library-list"></div><section class="feature-card">${head('Models on this device','<span id="modelFolderPath">No folder selected.</span>',button('Choose folder','choose-models','','id="chooseModelsBtn"'))}<div class="library-toolbar">${search('modelSearch','Search cached models')}${select('modelTypeFilter',[['all','All formats'],['gguf','GGUF'],['huggingface','HF cache']])}${button('Scan','scan-models','refresh','id="scanModelsBtn"')}</div><p id="modelScanStatus" class="settings-note" role="status">Discovery reads metadata only, never model weights.</p><div id="localModelList" class="library-list"></div></section>${note('Use setup selects a preference, not a running server. Launch commands are copied for you to run; June does not execute them.')}`)+
page('cookbook','download',`<section class="feature-card"><h3>Download from Hugging Face</h3>${note('Prepare an explicit download command. No background downloads or dependency installation.')}<form id="downloadForm">${field('Repository',input('downloadRepo','text','required placeholder="owner/model-repository" maxlength="200"'))}${field('Model filename',input('downloadFile','text','required placeholder="model-Q4_K_M.gguf" maxlength="1000"'))}${submit('Prepare download')}</form>${field('Command <span class="shell-label"></span>','<textarea id="downloadCommand" readonly rows="3"></textarea>')}<div class="library-actions">${button('Copy command','copy-download','copy')}${button('Open repository','open-model-page','external')}</div></section>${note('Requires the hf CLI. Gated repositories may need authentication and license acceptance in your terminal. After downloading, choose the cache folder in Launch.')}`,true)+
page('cookbook','dependencies',head('Local environment','Detect installed tools and available system information.',button('Check now','check-dependencies','','id="checkDepsBtn"'))+'<p id="dependencyStatus" class="settings-note" role="status">Nothing has been checked.</p><div id="hardwareInfo" class="feature-card" hidden></div><div id="dependencyList" class="library-list"></div>'+note('No invented VRAM, speed, or fit ratings. Model file size is not total runtime memory.'),true)+
page('cookbook','settings',`<h3>Defaults for new setups</h3><form id="cookbookPreferencesForm">${field('Runtime',runtime('cookbookRuntime'))}${field('Model server endpoint',input('cookbookEndpoint','url','required'))}${field('Context budget',input('cookbookContext','number','min="1024" max="2097152" required'))}${submit('Save defaults')}</form>${note('This is the model server, not June\'s pipeline API. Configure the latter in Settings > Backend.')}`,true)+`</div>`,'cookbook-dialog','<span id="cookbookStatus" role="status">Models and setups stay on this device.</span><button class="secondary-button" data-close="cookbookDialog">Done</button>')}
${dialog('recipeDialog','Model setup',`<form id="recipeForm" class="feature-body"><div class="form-row">${field('Name',input('recipeName','text','required maxlength="120"'))}${field('Runtime',runtime('recipeRuntime'))}</div>${field('Model identifier',input('recipeModel','text','required maxlength="500"'))}${field('Local model path (optional)',input('recipePath','text','maxlength="4096"'))}${field('Model server endpoint',input('recipeEndpoint','url','required'))}${field('Context budget',input('recipeContext','number','min="1024" max="2097152" required'))}${field('Launch command <span class="shell-label"></span>','<textarea id="recipeCommand" rows="3" readonly></textarea>')}${button('Copy launch command','copy-launch','copy')}${note('Commands are never run by June. Downloaded models are untrusted; this setup never enables remote code.')}${submit('Save setup')}</form>`,'recipe-dialog')}
`;
if (typeof document !== 'undefined' && !document.getElementById('knowledgeDialog')) document.body.insertAdjacentHTML('beforeend',extraMarkup);
