/* Data-only helpers. No storage, networking, or code execution. */
export const KNOWLEDGE_KEY='june.knowledge.v1', COOKBOOK_KEY='june.cookbook.v1';
export const knowledgeDefaults={memoriesEnabled:true,skillsEnabled:true,maxSkills:3};
export const cookbookDefaults={runtime:'llama.cpp',endpoint:'http://127.0.0.1:8080',context:32768};
const text=(v,max=20000)=>typeof v==='string'?v.trim().slice(0,max):'';
const arr=v=>Array.isArray(v)?v:[];
export function validEndpoint(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password&&!u.search&&!u.hash;}catch{return false;}}
export function normalizeKnowledge(raw={}){const p=raw?.preferences||{};return {version:1,preferences:{memoriesEnabled:typeof p.memoriesEnabled==='boolean'?p.memoriesEnabled:true,skillsEnabled:typeof p.skillsEnabled==='boolean'?p.skillsEnabled:true,maxSkills:Number.isInteger(p.maxSkills)&&p.maxSkills>=0&&p.maxSkills<=20?p.maxSkills:3},memories:arr(raw?.memories).slice(0,1000).map(m=>({id:text(m?.id,100),content:text(m?.content,8000),category:['fact','preference','project','instruction'].includes(m?.category)?m.category:'fact',projectPath:text(m?.projectPath,4096),enabled:m?.enabled!==false,createdAt:Number(m?.createdAt)||0,updatedAt:Number(m?.updatedAt)||0})).filter(m=>m.id&&m.content),skills:arr(raw?.skills).slice(0,500).map(s=>({id:text(s?.id,100),title:text(s?.title,120),when:text(s?.when,4000),how:text(s?.how,30000),tags:arr(s?.tags).filter(t=>typeof t==='string').slice(0,20).map(t=>text(t,40)),source:text(s?.source,2000),projectPath:text(s?.projectPath,4096),enabled:s?.enabled!==false,approved:s?.approved===true,createdAt:Number(s?.createdAt)||0,updatedAt:Number(s?.updatedAt)||0})).filter(s=>s.id&&s.title&&s.how)};}
export function normalizeCookbook(raw={}){const p=raw?.preferences||{},context=v=>Number.isInteger(v)&&v>=1024&&v<=2097152?v:32768,runtime=v=>['llama.cpp','ollama','custom'].includes(v)?v:'custom';return {version:1,activeRecipeId:text(raw?.activeRecipeId,100),preferences:{runtime:p.runtime?runtime(p.runtime):'llama.cpp',endpoint:validEndpoint(p.endpoint)?p.endpoint:cookbookDefaults.endpoint,context:context(p.context)},recipes:arr(raw?.recipes).slice(0,200).map(r=>({id:text(r?.id,100),name:text(r?.name,120),model:text(r?.model,500),filePath:text(r?.filePath,4096),runtime:runtime(r?.runtime),endpoint:validEndpoint(r?.endpoint)?r.endpoint:cookbookDefaults.endpoint,context:context(r?.context)})).filter(r=>r.id&&r.name&&r.model)};}
export function eligibleKnowledge(lib,projectPath,temporary=false){if(temporary)return {memories:[],skills:[]};const scope=i=>!i.projectPath||i.projectPath===projectPath;return {memories:lib.preferences.memoriesEnabled?lib.memories.filter(m=>m.enabled&&scope(m)):[],skills:lib.preferences.skillsEnabled?lib.skills.filter(s=>s.enabled&&s.approved&&scope(s)).slice(0,lib.preferences.maxSkills):[]};}
export function buildContext(chat,lib,projectPath,temporary=false){const messages=arr(chat?.messages).map(m=>({role:m.role,content:m.content})),c=chat?.compaction;const valid=c&&typeof c.summary==='string'&&c.summary.trim()&&Number.isInteger(c.through)&&c.through>=0&&c.through<=messages.length;return {projectPath,mode:chat?.mode||'agent',contextBudget:chat?.contextBudget||32768,temporary,retention:temporary?'none':'local',memoryRead:!temporary&&lib.preferences.memoriesEnabled,memoryWrite:false,messages:valid?[{role:'system',content:'User-reviewed conversation summary:\n'+c.summary},...messages.slice(c.through)]:messages,...eligibleKnowledge(lib,projectPath,temporary)};}
export function serializeChat(chat){return '# '+(text(chat?.title,120)||'June chat')+'\n\n'+arr(chat?.messages).map(m=>'## '+(m.role==='user'?'You':m.role==='assistant'?'June':'Note')+'\n\n'+m.content).join('\n\n')+'\n';}
export function memoryCandidates(source,filename){if(typeof source!=='string'||source.length>1048576)throw new Error('Import must be smaller than 1 MB.');if(/\.json$/i.test(filename)){const p=JSON.parse(source);if(p?.version!==1||(!Array.isArray(p.memories)&&!Array.isArray(p.skills)))throw new Error('Use a June knowledge v1 JSON export.');return [...arr(p.memories).map(m=>({kind:'memory',content:text(m?.content,8000),category:['fact','preference','project','instruction'].includes(m?.category)?m.category:'fact'})),...arr(p.skills).map(s=>({kind:'skill',title:text(s?.title,120),when:text(s?.when,4000),how:text(s?.how,30000),tags:arr(s?.tags).filter(t=>typeof t==='string').slice(0,20),source:text(s?.source,2000)}))].filter(i=>i.kind==='memory'?i.content:i.title&&i.how).slice(0,100);}return source.split(/\n\s*\n/).map(s=>s.trim()).filter(Boolean).slice(0,100).map(content=>({kind:'memory',content:content.slice(0,8000),category:'fact'}));}
export function parseSkill(source,filename='SKILL.md'){if(typeof source!=='string'||source.length>100000)throw new Error('SKILL.md must be smaller than 100 KB.');const name=source.match(/^name:\s*["']?([^\n"']+)["']?\s*$/m)?.[1],description=source.match(/^description:\s*["']?([^\n"']+)["']?\s*$/m)?.[1],heading=source.match(/^#\s+(.+)$/m)?.[1],body=source.replace(/^---\s*\r?\n[\s\S]*?\r?\n---\s*\r?\n/,'').trim();if(!body)throw new Error('This skill has no instructions.');return {kind:'skill',title:text(name||heading||filename.replace(/\.md$/i,''),120),when:text(description||'Use when this procedure matches the task.',4000),how:body.slice(0,30000),tags:[],source:filename};}
export function duplicateMemoryIds(memories){const seen=new Set(),duplicates=[];for(const m of memories){const key=JSON.stringify([m.projectPath,m.category,m.content.trim().replace(/\s+/g,' ').toLowerCase()]);if(seen.has(key))duplicates.push(m.id);else seen.add(key);}return duplicates;}
export function quoteArgument(value,platform='posix'){const v=String(value);if(/[\0\r\n]/.test(v))throw new Error('Commands cannot contain line breaks or null characters.');return platform==='win32'?"'"+v.replaceAll("'","''")+"'":"'"+v.replaceAll("'","'\\''")+"'";}
export function launchCommand(recipe,platform){const q=v=>quoteArgument(v,platform);if(recipe.runtime==='custom')return '# Start your custom pipeline separately, then configure its endpoint in Settings.';if(recipe.runtime==='ollama')return 'ollama run '+q(recipe.model);if(!recipe.filePath||!/\.gguf$/i.test(recipe.filePath))return '# Select a GGUF file to generate a llama.cpp launch command.';const u=new URL(recipe.endpoint),port=u.port||(u.protocol==='https:'?'443':'80');return `llama-server --model ${q(recipe.filePath)} --ctx-size ${recipe.context} --host 127.0.0.1 --port ${port}`;}
export function downloadCommand(repo,filename,platform){if(!/^[A-Za-z0-9][A-Za-z0-9._-]*\/[A-Za-z0-9][A-Za-z0-9._-]*$/.test(repo))throw new Error('Enter a Hugging Face repository as owner/model.');if(!filename||filename.startsWith('/')||filename.startsWith('-')||filename.split(/[\\/]/).includes('..')||/[\0\r\n]/.test(filename))throw new Error('Enter a repository-relative model filename.');return 'hf download '+quoteArgument(repo,platform)+' '+quoteArgument(filename,platform);}
