const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {pathToFileURL}=require('node:url');
const {registerFeatures,scanModelFolder,inspectEnvironment,skillUrl,fetchSkillText,exportHtml,inside,safeName}=require('../electron/features.cjs');
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'june-test-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));return root;}
test('Containment rejects sibling paths without rejecting dot names',()=>{assert.ok(inside('/root','/root/..config'));assert.equal(inside('/root','/root-sibling/file'),false);});
test('Scan finds real GGUF and HF cache metadata',async t=>{const root=await fixture(t);await fs.writeFile(path.join(root,'a.gguf'),'GGUF');await fs.mkdir(path.join(root,'models--org--model','blobs'),{recursive:true});await fs.writeFile(path.join(root,'models--org--model','blobs','hash'),'model');const r=await scanModelFolder(root);assert.equal(r.models.length,2);assert.equal(r.models.find(m=>m.format==='gguf').size,4);assert.equal(r.models.find(m=>m.format==='huggingface').modelId,'org/model');});
test('Scan rejects out-of-root links and ignores directory loops',async t=>{const root=await fixture(t),out=await fixture(t);await fs.writeFile(path.join(out,'secret.gguf'),'secret');try{await fs.symlink(path.join(out,'secret.gguf'),path.join(root,'leak.gguf'));await fs.symlink(root,path.join(root,'loop'),'dir');}catch(e){if(e.code==='EPERM'){t.skip('Symlink privilege unavailable');return;}throw e;}const r=await scanModelFolder(root);assert.equal(r.models.length,0);assert.ok(r.skipped>=1);});
test('Scan reports result cap',async t=>{const root=await fixture(t);for(let i=0;i<5;i++)await fs.writeFile(path.join(root,i+'.gguf'),'x');const r=await scanModelFolder(root,{maxModels:2});assert.equal(r.models.length,2);assert.equal(r.truncated,true);});
test('GitHub skill URLs are allowlisted',()=>{assert.equal(skillUrl('https://github.com/o/r/tree/main/skill'),'https://raw.githubusercontent.com/o/r/main/skill/SKILL.md');for(const u of ['file:///etc/passwd','https://evil.test/SKILL.md','https://github.com/o/r/blob/main/SKILL.md?key=x'])assert.throws(()=>skillUrl(u));});
test('Skill fetch bounds stream bytes and rejects HTML',async()=>{const url='https://raw.githubusercontent.com/o/r/main/SKILL.md';assert.match((await fetchSkillText(url,async()=>new Response('# Skill'))).content,/# Skill/);await assert.rejects(fetchSkillText(url,async()=>new Response('x'.repeat(100001))),/100 KB/);await assert.rejects(fetchSkillText(url,async()=>new Response('<html>bad</html>')),/web page/);});
test('Environment invokes only fixed version commands without shell',async()=>{const calls=[];const r=await inspectEnvironment(async(cmd,args,opts)=>{calls.push({cmd,args,opts});return {stdout:'version 1'};});assert.equal(calls.length,5);assert.ok(calls.every(c=>c.opts.shell===false&&c.opts.timeout===3500));assert.ok(r.ram>0);});
test('PDF HTML escapes scripts and uses network-blocking CSP',()=>{const html=exportHtml('<img src=x>','<script>evil()</script>');assert.ok(!html.includes('<script>'));assert.match(html,/&lt;script&gt;/);assert.match(html,/default-src 'none'/);assert.equal(safeName('../../evil.md','md'),'_.._evil.md');});
function setup(root,saveDialog){const handlers=new Map(),frame={url:pathToFileURL(path.resolve(__dirname,'../index.html')).href},contents={};contents.mainFrame=frame;const win={isDestroyed:()=>false};registerFeatures({app:{getPath:()=>root,on:()=>{}},BrowserWindow:{fromWebContents:wc=>wc===contents?win:null},dialog:{showSaveDialog:saveDialog},ipcMain:{handle:(n,f)=>handlers.set(n,f)},shell:{},clipboard:{writeText:()=>{}}});return {handlers,event:{sender:contents,senderFrame:frame}};}
test('New IPC rejects foreign windows and subframes',()=>{const {handlers,event}=setup('/tmp');assert.equal(handlers.get('june:copy-text')(event,'text'),true);assert.throws(()=>handlers.get('june:copy-text')({...event,sender:{}},'secret'),/main window/);assert.throws(()=>handlers.get('june:copy-text')({...event,senderFrame:{...event.senderFrame}},'secret'),/main window/);});
test('Export honors cancel and the user-selected path',async t=>{const root=await fixture(t);let canceled=true;const {handlers,event}=setup(root,async()=>({canceled,filePath:path.join(root,'selected.md')})),p={format:'md',text:'# June',name:'chat.md',title:'June'};assert.equal((await handlers.get('june:save-artifact')(event,p)).saved,false);assert.deepEqual(await fs.readdir(root),[]);canceled=false;assert.equal((await handlers.get('june:save-artifact')(event,p)).saved,true);assert.equal(await fs.readFile(path.join(root,'selected.md'),'utf8'),'# June');});
