'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {pathToFileURL}=require('node:url'),{execFile}=require('node:child_process'),{promisify}=require('node:util');
const run=promisify(execFile),MAX_TEXT=2*1024*1024;
const inside=(root,target)=>{const rel=path.relative(root,target);return rel!=='..'&&!rel.startsWith('..'+path.sep)&&!path.isAbsolute(rel);};
function validateText(v,max=MAX_TEXT){if(typeof v!=='string'||Buffer.byteLength(v,'utf8')>max)throw new Error('Text is missing or too large.');return v;}
function safeName(v,format){return (String(v||'June export').replace(/\.(md|pdf|json)$/i,'').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/^\.+/,'').slice(0,100).trim()||'June export')+'.'+format;}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function exportHtml(title,text){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'"><title>${escapeHtml(title)}</title><style>@page{size:A4;margin:17mm}body{font-family:Arial,sans-serif;font-size:10pt;color:#202730}h1{font-size:20pt;margin:0 0 8mm}.caption{font-size:9pt;color:#606a76;margin-bottom:8mm}pre{font-family:Consolas,monospace;font-size:9pt;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.55}</style></head><body><h1>${escapeHtml(title)}</h1><div class="caption">Exported from June</div><pre>${escapeHtml(text)}</pre></body></html>`;}
function skillUrl(raw){const u=new URL(validateText(raw,4000));if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.port)throw new Error('Use a public HTTPS GitHub Markdown URL without credentials or query parameters.');const s=u.pathname.split('/').filter(Boolean);if(s.some(p=>decodeURIComponent(p)==='..'||/[\\\0]/.test(decodeURIComponent(p))))throw new Error('Invalid path.');if(u.hostname==='raw.githubusercontent.com'&&s.length>=4&&/\.md$/i.test(s.at(-1)))return u.href;if(u.hostname==='github.com'&&s.length>=4&&['blob','tree'].includes(s[2])){const [owner,repo,kind,ref,...file]=s;if(kind==='tree')file.push('SKILL.md');if(!file.length||!/\.md$/i.test(file.at(-1)))throw new Error('Choose a Markdown file or skill folder. Use a raw URL for branch names containing slashes.');return `https://raw.githubusercontent.com/${owner}/${repo}/${ref}/${file.join('/')}`;}throw new Error('Only public GitHub Markdown skill files are supported.');}
async function fetchSkillText(raw,fetcher=fetch){const source=skillUrl(raw),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);let reader;try{const r=await fetcher(source,{signal:controller.signal,redirect:'error',headers:{Accept:'text/plain'}});if(!r.ok)throw new Error('GitHub returned HTTP '+r.status+'.');if(Number(r.headers.get('content-length'))>100000)throw new Error('Skill exceeds 100 KB.');if(!r.body)throw new Error('Empty response.');reader=r.body.getReader();let size=0;const chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>100000)throw new Error('Skill exceeds 100 KB.');chunks.push(Buffer.from(value));}const content=Buffer.concat(chunks).toString('utf8');if(/^\s*(<!doctype html|<html)/i.test(content))throw new Error('URL returned a web page, not Markdown.');return {source,content};}finally{clearTimeout(timer);if(reader){await reader.cancel().catch(()=>{});reader.releaseLock();}}}
async function scanModelFolder(selectedRoot,limits={}){
 const root=await fs.realpath(selectedRoot);if(!(await fs.stat(root)).isDirectory())throw new Error('Model folder is unavailable.');
 const maxVisits=limits.maxVisits||20000,maxModels=limits.maxModels||200,maxDepth=limits.maxDepth||12;let visited=0,truncated=false,skipped=0;
 const models=[],queue=[{path:root,depth:0}],ignored=new Set(['.git','node_modules','.venv','venv','.locks']);
 async function cacheSize(cache){const stack=[{path:cache,depth:0}],seen=new Set();let total=0;while(stack.length){const current=stack.pop();let handle;try{const real=await fs.realpath(current.path);if(!inside(root,real)){skipped++;continue;}handle=await fs.opendir(real);}catch{skipped++;continue;}
  for await(const e of handle){if(++visited>maxVisits){truncated=true;return null;}const target=path.join(current.path,e.name);if(e.isDirectory()){if(!ignored.has(e.name)){if(current.depth>=maxDepth){truncated=true;return null;}stack.push({path:target,depth:current.depth+1});}continue;}if(!e.isFile()&&!e.isSymbolicLink())continue;try{const real=await fs.realpath(target);if(!inside(root,real)){skipped++;continue;}const st=await fs.stat(real);if(!st.isFile())continue;const id=st.ino?st.dev+':'+st.ino:real;if(!seen.has(id)){seen.add(id);total+=st.size;}}catch{skipped++;}}}return total;}
 while(queue.length&&!truncated){const current=queue.shift();let handle;try{const real=await fs.realpath(current.path);if(!inside(root,real)){skipped++;continue;}handle=await fs.opendir(real);}catch{skipped++;continue;}
  for await(const e of handle){if(++visited>maxVisits||models.length>=maxModels){truncated=true;break;}const target=path.join(current.path,e.name);if(e.isDirectory()){if(ignored.has(e.name))continue;if(e.name.startsWith('models--')){const modelId=e.name.slice(8).split('--').join('/');models.push({name:modelId,modelId,path:target,format:'huggingface',size:await cacheSize(target)});if(truncated)break;}else if(current.depth<maxDepth)queue.push({path:target,depth:current.depth+1});else{truncated=true;break;}}
   else if((e.isFile()||e.isSymbolicLink())&&/\.gguf$/i.test(e.name)){try{const real=await fs.realpath(target);if(!inside(root,real)){skipped++;continue;}const st=await fs.stat(real);if(st.isFile())models.push({name:e.name,modelId:e.name.replace(/\.gguf$/i,''),path:target,format:'gguf',size:st.size});}catch{skipped++;}}
  }
 }models.sort((a,b)=>a.name.localeCompare(b.name));return {models,truncated,skipped,visited};
}
async function inspectEnvironment(runner=run){const commands=[['Git','git',['--version']],['Python',process.platform==='win32'?'python':'python3',['--version']],['Ollama','ollama',['--version']],['llama.cpp server','llama-server',['--version']],['Hugging Face CLI','hf',['--help']]];const dependencies=await Promise.all(commands.map(async([name,command,args])=>{try{const r=await runner(command,args,{cwd:os.homedir(),windowsHide:true,timeout:3500,maxBuffer:32768,shell:false}),raw=(r.stdout||r.stderr||'').replace(/\x1b\[[0-9;]*m/g,'').trim();return {name,available:true,version:name==='Hugging Face CLI'?'CLI available':raw.split(/\r?\n/)[0].slice(0,180)||'Available'};}catch(e){return {name,available:false,reason:e.code==='ENOENT'?'Not found on PATH':e.killed?'Version check timed out':'Could not run version check'};}}));const cpus=os.cpus();return {platform:process.platform,cpu:cpus[0]?.model||'Unknown CPU',logicalCpus:cpus.length,ram:os.totalmem(),freeRam:os.freemem(),dependencies};}
function registerFeatures({app,BrowserWindow,dialog,ipcMain,shell,clipboard}){
 const indexUrl=pathToFileURL(path.join(__dirname,'..','index.html')).href;let rootCache=null,queue=Promise.resolve(),scan=null,inspection=null,exportBusy=false;
 const config=()=>path.join(app.getPath('userData'),'cookbook-folder.json');
 async function getRoot(){if(rootCache!==null)return rootCache;try{if((await fs.stat(config())).size>16384)throw new Error('Invalid config.');const d=JSON.parse(await fs.readFile(config(),'utf8'));rootCache=typeof d.path==='string'&&path.isAbsolute(d.path)?d.path:'';}catch{rootCache='';}return rootCache;}
 function sender(e){const win=BrowserWindow.fromWebContents(e.sender);if(!win||win.isDestroyed()||e.senderFrame!==e.sender.mainFrame||e.senderFrame?.url!==indexUrl)throw new Error('This operation is only available to June\'s main window.');return win;}
 const handle=(channel,fn)=>ipcMain.handle(channel,(e,...args)=>fn(sender(e),...args));
 handle('june:copy-text',(_w,text)=>{clipboard.writeText(validateText(text));return true;});
 handle('june:cookbook-info',async()=>({platform:process.platform,modelRoot:await getRoot()}));
 handle('june:choose-model-folder',async win=>{const current=await getRoot(),r=await dialog.showOpenDialog(win,{title:'Choose a model folder or Hugging Face hub cache',buttonLabel:'Use model folder',properties:['openDirectory'],defaultPath:current||process.env.HF_HUB_CACHE||path.join(process.env.HF_HOME||path.join(os.homedir(),'.cache','huggingface'),'hub')});if(r.canceled||!r.filePaths[0])return null;const root=await fs.realpath(r.filePaths[0]);if(!(await fs.stat(root)).isDirectory())throw new Error('Choose a folder.');const write=async()=>{await fs.mkdir(path.dirname(config()),{recursive:true});await fs.writeFile(config()+'.tmp',JSON.stringify({version:1,path:root}),{encoding:'utf8',mode:0o600});await fs.rename(config()+'.tmp',config());rootCache=root;};queue=queue.then(write,write);await queue;return {path:root};});
 handle('june:scan-models',async()=>{const root=await getRoot();if(!root)throw new Error('Choose a model folder first.');if(scan)return scan;scan=scanModelFolder(root).finally(()=>{scan=null;});return scan;});
 handle('june:inspect-environment',()=>{if(inspection)return inspection;inspection=inspectEnvironment().finally(()=>{inspection=null;});return inspection;});
 handle('june:fetch-skill',(_w,url)=>fetchSkillText(url));
 handle('june:open-model-page',async(_w,repo)=>{if(typeof repo!=='string'||!/^[A-Za-z0-9][A-Za-z0-9._-]*\/[A-Za-z0-9][A-Za-z0-9._-]*$/.test(repo))throw new Error('Invalid Hugging Face repository.');await shell.openExternal('https://huggingface.co/'+repo);return true;});
 handle('june:save-artifact',async(win,p)=>{if(exportBusy)throw new Error('An export dialog is already open.');if(!p||!['md','json','pdf'].includes(p.format))throw new Error('Unsupported export format.');const text=validateText(p.text),title=validateText(p.title||'June chat',1000),name=safeName(p.name,p.format);exportBusy=true;let printWindow;try{const r=await dialog.showSaveDialog(win,{title:p.format==='pdf'?'Export chat as PDF':'Save June export',defaultPath:path.join(app.getPath(p.documents?'documents':'downloads'),name),filters:[{name:p.format.toUpperCase(),extensions:[p.format]}],properties:['showOverwriteConfirmation','createDirectory']});if(r.canceled||!r.filePath)return {saved:false};let output=text;if(p.format==='pdf'){printWindow=new BrowserWindow({show:false,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,javascript:false,partition:'june-export-'+Date.now()}});printWindow.webContents.setWindowOpenHandler(()=>({action:'deny'}));await printWindow.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent(exportHtml(title,text)));output=await printWindow.webContents.printToPDF({pageSize:'A4',printBackground:true,preferCSSPageSize:true});}await fs.writeFile(r.filePath,output,typeof output==='string'?{encoding:'utf8',mode:0o600}:undefined);return {saved:true,path:r.filePath};}finally{if(printWindow&&!printWindow.isDestroyed())printWindow.destroy();exportBusy=false;}});
 app.on('web-contents-created',(_e,contents)=>{if(contents.getLastWebPreferences?.().preload!==path.join(__dirname,'preload.cjs'))return;contents.on('will-navigate',(e,url)=>{if(url!==indexUrl)e.preventDefault();});contents.on('will-attach-webview',e=>e.preventDefault());});
}
module.exports={registerFeatures,scanModelFolder,inspectEnvironment,skillUrl,fetchSkillText,exportHtml,inside,safeName};
